# Homeassistant basic configuration
homeassistant:
  name: Home
  latitude: !secret homeassistant_latitude
  longitude: !secret homeassistant_longitude
  elevation: 400
  unit_system: metric
  time_zone: Europe/Amsterdam
  currency: EUR
  customize: !include customize.yaml
  packages: !include_dir_named intergrations/

# Configure a default setup of Home Assistant (frontend, api, etc)
default_config:

# Include scripts and scenes
script: !include scripts.yaml
scene: !include scenes.yaml
