---
# When all persons are away turn off all devices and lower temperature
- alias: "Schakel alle apparaten uit en stel de temperatuur in op 18 graden als alle personen niet thuis zijn"
  initial_state: 'on'
  trigger:
  - platform: state
    entity_id: group.all_persons
    to: not_home
    from: home
    for:
      hours: 0
      minutes: 10
      seconds: 0
  condition: []
  action:
  - service: light.turn_off
    target:
      area_id:
      - eetkamer
      - keuken
      - woonkamer
  - service: climate.set_temperature
    data:
      temperature: 18
    target:
      entity_id: climate.woonkamer
  mode: single
