---
# Set temperature when coming home between 08:00 and 21:30
- alias: "Stel de temperatuur in op 19 graden bij thuiskomst"
  initial_state: 'on'
  trigger:
  - platform: state
    entity_id: group.all_persons
    from: not_home
    to: home
    for:
      hours: 0
      minutes: 2
      seconds: 0
  condition:
  - condition: time
    after: '8:00'
    before: '21:30'
  action:
  - service: climate.set_temperature
    target:
      entity_id: climate.woonkamer
    data:
      temperature: 19
  mode: single
