---
# Turn off lights at bedtime when the TV turns off
- alias: "Lichten uit als de TV uit gaat rond bed tijd"
  initial_state: 'on'
  trigger:
  - platform: state
    entity_id: media_player.lg_oled_c9
    to: 'off'
    for:
      hours: 0
      minutes: 5
      seconds: 0
  condition:
  - condition: time
    after: '21:00'
    before: '03:00'
  action:
  - service: light.turn_off
    target:
      area_id:
      - eetkamer
      - keuken
      - woonkamer
  mode: single

# Turn off lights at 23:00 by default, if the TV is not on
- alias: "Lichten uit als de TV niet aan staat om 23:00"
  trigger:
  - platform: time
    at: '23:00'
  condition:
  - condition: state
    entity_id: media_player.lg_oled_c9
    state: 'off'
  action:
  - service: light.turn_off
    target:
      area_id:
      - eetkamer
      - keuken
      - woonkamer
  mode: single
