---
# Turn on lights for 60 seconds when motion is detected in hal
- alias: "Lichten aan in de hal bij beweging"
  initial_state: 'on'
  trigger:
  - platform: state
    entity_id: binary_sensor.philips_hue_motion_sensor_hal_occupancy
    from: 'off'
    to: 'on'
  condition:
  - condition: state
    entity_id: sun.sun
    state: below_horizon
  action:
  - service: light.turn_on
    target:
      entity_id: light.group_hal
    data:
      brightness_pct: 80
  - wait_for_trigger:
      platform: state
      entity_id: binary_sensor.philips_hue_motion_sensor_hal_occupancy
      from: 'on'
      to: 'off'
  - delay: 60
  - service: light.turn_off
    target:
      entity_id: light.group_hal
  mode: restart
  max_exceeded: silent
