---
# Turn on lights for 60 seconds when motion is detected in overloop
- alias: "Lichten aan in de overloop bij beweging"
  initial_state: 'on'
  trigger:
  - platform: state
    entity_id: binary_sensor.philips_hue_motion_sensor_overloop_occupancy
    from: 'off'
    to: 'on'
  condition:
  - condition: state
    entity_id: sun.sun
    state: below_horizon
  action:
  - service: light.turn_on
    target:
      entity_id: light.group_overloop
    data:
      brightness_pct: '{% if (now().hour >= 22 or now().hour < 9) %}30{% else %} 80{% endif %}'
  - wait_for_trigger:
      platform: state
      entity_id: binary_sensor.philips_hue_motion_sensor_overloop_occupancy
      from: 'on'
      to: 'off'
  - delay: 60
  - service: light.turn_off
    target:
      entity_id: light.group_overloop
  mode: restart
  max_exceeded: silent
