---
# Turn on LG OLED C9 TV in living room
- alias: Turn on LG OLED C9 TV
  initial_state: 'on'
  trigger:
  - platform: webostv.turn_on
    entity_id: media_player.lg_oled_c9
  action:
  - service: wake_on_lan.send_magic_packet
    data:
      mac: !secret webostv_mac
